spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crmsight
    username: postgres
    password: 100037
  redis:
    cluster:
      nodes: 10.237.120.176:6379,10.237.120.177:6379,10.237.120.178:6379,10.237.120.176:6380,10.237.120.177:6380,10.237.120.178:6380
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: c65178899Sc_ # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.crm.crmsight: debug
