spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crmsight
    username: postgres
    password: 100037
  redis:
    host: 10.237.120.176 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: c65178899Sc_ # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.crm.crmsight: info
