# 配置postgre
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crmsight
    username: postgres
    password: 100037
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    cluster:
      nodes: 10.237.120.176:6379,10.237.120.177:6379,10.237.120.178:6379,10.237.120.176:6380,10.237.120.177:6380,10.237.120.178:6380 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: c65178899Sc_ # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

mybatis-plus:
  mapper-locations:
    - classpath:com/crm/crmsight/modules/ums/mapper/*.xml
#    - classpath:/modules/**/*.xml
#    - classpath*:com/**/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout


#  datasource:
#    url: jdbc:sqlserver://10.237.1.250;selectMethod=cursor
#    username: sa
#    password: c85130268Sc_
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
